In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import Perceptron
import sklearn.metrics as metric
import numpy as np

In [38]:
#######Example of two output#######

x_train = [[1, 0,0,0], 
           [1, 1,0,1],
           [0, 1,0,1],
           [0, 0,0,0],
           [1, 1,0,1],
           [1, 0,1,1],
           [0, 1,1,1],
           [0, 1,2,1],
           [1, 2,2,1],
           [0, 2,2,2]
          ]                    
y_train = [ [1], 
            [1],
            [2],
            [1],
            [1],
            [2],
            [2],
            [0],
            [0],
            [0]]
           
                

x_test = x_train
y_true = y_train
x_test2=[[0,0,2,1]]

In [96]:
#######Multi Layer Perceptron#######

mlp = MLPClassifier(solver='sgd', hidden_layer_sizes=(100),
                    activation='logistic') # set the method
mlp.fit(x_train, y_train)                    # training
y_pred = mlp.predict(x_test)                      # prediction
print(y_pred)                                      # show the output
accuracy = metric.accuracy_score(np.array(y_true).flatten(),
                               np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score
y_pred2 = mlp.predict(x_test2)                      # prediction
print(y_pred2)                                      # show the output

[1 1 1 1 1 1 1 1 1 1]
acuracy= 0.4
[1]


C:\Users\asus\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [63]:
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
mlp.coefs_                                  # a list of weight matrices,
                                            # where weight matrix at index i represents
                                            # the weights between layer i and layer i+1
#print([coef.shape for coef in mlp.intercept_])
#mlp.intercept_

[(4, 100), (100, 3)]


[array([[-6.71916569e-01, -3.36088411e-01, -7.11173585e-01,
          3.26045272e-03,  6.79453958e-03, -4.04545858e-01,
          1.07882601e-01,  5.19724065e-01, -2.37386582e-01,
         -3.90850961e-01, -3.01976934e-01,  9.62834683e-01,
          2.45978707e-01,  8.00602260e-01, -2.94395936e-01,
         -4.20916943e-02, -2.52055812e-01,  3.49641701e-01,
          1.23566197e-01, -5.18287050e-01,  1.96422280e-01,
          5.74125248e-01,  8.89571842e-01, -1.26765535e-03,
         -1.02195603e+00,  9.63647851e-01, -8.96335078e-01,
         -8.28065029e-01, -1.76074780e-01, -5.08251734e-01,
          8.35003578e-01,  8.42177150e-01,  1.49153920e-01,
          5.85477899e-01,  6.28616807e-01,  4.72258637e-01,
          1.13083408e+00, -8.60635289e-01, -5.01597981e-02,
          5.05733494e-01,  6.90237227e-01, -5.56412800e-01,
          5.90732632e-01, -6.68290057e-02, -3.58128730e-01,
         -5.46190581e-01, -1.80781466e-01, -4.82326120e-01,
          1.36600194e+00, -3.66153697e-0

In [97]:
#######Multi Layer Perceptron#######

mlp = MLPClassifier(solver='sgd', hidden_layer_sizes=(100),
                    activation='tanh') # set the method
mlp.fit(x_train, y_train)                    # training
y_pred = mlp.predict(x_test)                      # prediction
print(y_pred)                                      # show the output
accuracy = metric.accuracy_score(np.array(y_true).flatten(),
                               np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score
y_pred2 = mlp.predict(x_test2)                      # prediction
print(y_pred2)                                      # show the output

[1 1 1 1 1 1 0 0 0 0]
acuracy= 0.7
[0]


C:\Users\asus\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [58]:
print([coef.shape for coef in mlp.coefs_])  # size of synapsis weights
mlp.coefs_                                  # a list of weight matrices,
                                            # where weight matrix at index i represents
                                            # the weights between layer i and layer i+1
#print([coef.shape for coef in mlp.intercept_])
#mlp.intercept_

[(4, 100), (100, 3)]


[array([[ 0.23625265, -0.24333899, -0.08789213,  0.00307522,  0.09972189,
          0.19103335, -0.19438655,  0.04586059, -0.07269484,  0.13417227,
         -0.32688322, -0.05482979, -0.18912242, -0.15970543,  0.21914652,
         -0.19256116,  0.29975016, -0.28177229, -0.11068636,  0.0714341 ,
          0.10088715,  0.36070778,  0.11923344, -0.04217217, -0.19304296,
          0.1830071 ,  0.17541992, -0.1193361 ,  0.16017821, -0.22915083,
         -0.2215062 , -0.28402916, -0.10653545, -0.19314787,  0.19155054,
         -0.19821834,  0.18137978,  0.32127013,  0.06904207,  0.04248512,
         -0.33636025, -0.33801597,  0.08163077,  0.19647128, -0.03752228,
          0.13431753, -0.21522274, -0.12261626, -0.26311435,  0.10142829,
         -0.07081268,  0.02704671,  0.15782209,  0.17907903,  0.07839575,
          0.08615833,  0.02386624, -0.34733015, -0.2407867 , -0.12140021,
          0.07744846, -0.13044201,  0.00719988,  0.07394176, -0.3078933 ,
          0.06256102, -0.04435948,  0.

In [98]:
#######Multi Layer Perceptron#######

mlp = MLPClassifier(solver='sgd', hidden_layer_sizes=(100),
                    activation='relu') # set the method
mlp.fit(x_train, y_train)                    # training
y_pred = mlp.predict(x_test)                      # prediction
print(y_pred)                                      # show the output
accuracy = metric.accuracy_score(np.array(y_true).flatten(),
                               np.array(y_pred).flatten(), normalize=True)
print('acuracy=',accuracy)                         # show accracy score
y_pred2 = mlp.predict(x_test2)                      # prediction
print(y_pred2)                                      # show the output

[1 1 1 1 1 2 0 0 0 0]
acuracy= 0.8
[0]


C:\Users\asus\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
